# Base config for all devices, ref.: https://esphome.io/components/packages.html
logger:

api:
  encryption:
    key: !secret esphome_api_password

ota:
  - platform: esphome
    password: !secret esphome_api_password

wifi:
  networks:
  - ssid: !secret wifi1_ssid
    password: !secret wifi1_password
  - ssid: !secret wifi2_ssid
    password: !secret wifi2_password
  - ssid: !secret wifi3_ssid
    password: !secret wifi3_password

  manual_ip:
    gateway: 10.10.10.1
    subnet: 255.0.0.0
    dns1: 10.10.10.100

  # Fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret esphome_fallback_ap_password

captive_portal:

web_server:
